---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-mdsanima
spec:
  replicas: 10
  selector:
    matchLabels:
      app: hello-mdsanima
  template:
    metadata:
      labels:
        app: hello-mdsanima
    spec:
      containers:
      - name: hello-mdsanima
        image: mdsanima/k3s-hello-mdsanima:latest
        imagePullPolicy: "Always"
        resources:
          limits:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: hello-mdsanima
spec:
  type: ClusterIP
  selector:
    app: hello-mdsanima
  ports:
  - port: 80
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-mdsanima
  labels:
    name: hello-mdsanima
spec:
  rules:
  - host: mdsanima.dev.local
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: hello-mdsanima
            port:
              number: 80
