/** Copyright © 2023 Marcin Różewski MDSANIMA */

// import { Inter } from "next/font/google"
import Head from "next/head"
import Image from "next/image"

import styles from "@mdsanima-lab/styles/Home.module.css"

// const inter = Inter({ subsets: ["latin"] })

export default function Home() {
  return (
    <>
      <Head>
        <title>MDSANIMA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/mdsanima_logo_rc1_default_10_red.svg" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center} style={{ minHeight: "100vh" }}>
          <Image
            className={styles.logo}
            src="/mdsanima_inline_rc3_flat_32_light.svg"
            alt="MDSANIMA Inline Logo"
            width={247}
            height={24}
            priority
          />
          <div className={styles.mdsanima}>
            <Image src="/mdsanima_logo_rc1_default_10_red.svg" alt="MDSANIMA Logo" width={50} height={50} priority />
          </div>
        </div>
      </main>
    </>
  )
}
