# Copyright (c) 2023-2024 MDSANIMA DEV. All rights reserved.
# Licensed under the MIT license.

# This file is used for syncing GitHub repository labels defined in the `.github/labels.yml` file.
# Documentation: https://github.com/Financial-Times/github-label-sync/#label-config-file

# Workflow setup
name: Sync Labels

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
      - .github/workflows/labels.yml

jobs:
  sync-labels:
    name: Sync Labels
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Syncing labels
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
